services:
    # bank code component
    Czechphp\CzechBankAccount\Loader\BankCode\LoaderInterface:
        alias: czech_bank_account.bank_code_loader

    czech_bank_account.bank_code_loader:
        class: Czechphp\CzechBankAccount\Loader\BankCode\FilesystemLoader

    # constant symbol component
    Czechphp\CzechBankAccount\ConstantSymbol\Loader\LoaderInterface:
        alias: czech_bank_account.constant_symbol_loader

    czech_bank_account.constant_symbol_loader:
        class: Czechphp\CzechBankAccount\ConstantSymbol\Loader\ArrayRequireLoader

    Czechphp\CzechBankAccount\ConstantSymbol\Filter\FilterInterface:
        alias: czech_bank_account.constant_symbol_filter

    czech_bank_account.constant_symbol_filter:
        class: Czechphp\CzechBankAccount\ConstantSymbol\Filter\ArrayCacheFilter
        arguments: ['@Czechphp\CzechBankAccount\ConstantSymbol\Filter\Filter']

    Czechphp\CzechBankAccount\ConstantSymbol\Filter\Filter:
        arguments: ['@czech_bank_account.constant_symbol_loader']

    # form types
    Czechphp\CzechBankAccountBundle\Form\Type\BankCodeType:
        arguments: ['@czech_bank_account.bank_code_loader']
        tags: ['form.type']

    # symfony validators
    Czechphp\CzechBankAccountBundle\Validator\Constraints\BankAccountNumberValidator:
        arguments: ['@Czechphp\CzechBankAccount\Validator\BankAccountNumberValidator']
        tags: ['validator.constraint_validator']

    Czechphp\CzechBankAccountBundle\Validator\Constraints\BankCodeValidator:
        arguments: ['@Czechphp\CzechBankAccount\Validator\BankCodeValidator']
        tags: ['validator.constraint_validator']

    Czechphp\CzechBankAccountBundle\Validator\Constraints\VariableSymbolValidator:
        arguments: ['@Czechphp\CzechBankAccount\Validator\VariableSymbolValidator']
        tags: ['validator.constraint_validator']

    Czechphp\CzechBankAccountBundle\Validator\Constraints\ConstantSymbolValidator:
        arguments: ['@Czechphp\CzechBankAccount\Validator\ConstantSymbolValidator']
        tags: ['validator.constraint_validator']

    Czechphp\CzechBankAccountBundle\Validator\Constraints\SpecificSymbolValidator:
        arguments: ['@Czechphp\CzechBankAccount\Validator\SpecificSymbolValidator']
        tags: ['validator.constraint_validator']

    # validators
    Czechphp\CzechBankAccount\Validator\BankAccountNumberValidator:

    Czechphp\CzechBankAccount\Validator\BankCodeValidator:
        arguments: ['@czech_bank_account.bank_code_loader']

    Czechphp\CzechBankAccount\Validator\VariableSymbolValidator:

    Czechphp\CzechBankAccount\Validator\ConstantSymbolValidator:
        arguments: ['@czech_bank_account.constant_symbol_filter']

    Czechphp\CzechBankAccount\Validator\SpecificSymbolValidator:
